export const products = [
  // Iphone
  {
    brand: "iphone",
    name: "iphone 1",
    description: "Silikonskal med MagSafe till iPhone 14 Pro Max",
    price: 595,
    amount: 1,
    colors: ["black", "blue", "red"],
    imageUrls: [
      "/src/assets/img/iphone/iphone-1-black.jpg",
      "/src/assets/img/iphone/iphone-1-blue.jpg",
      "/src/assets/img/iphone/iphone-1-red.jpg",
    ],
  },

  {
    brand: "iphone",
    name: "iphone 2",
    description:
      "OtterBox Figura Series-skal med MagSafe till iPhone 14 Pro Max",
    price: 695,
    amount: 1,
    colors: ["black", "blue", "pink"],
    imageUrls: [
      "/src/assets/img/iphone/iphone-2-black.jpg",
      "/src/assets/img/iphone/iphone-2-blue.jpg",
      "/src/assets/img/iphone/iphone-2-pink.jpg",
    ],
  },
  {
    brand: "iphone",
    name: "iphone 3",
    description: "OtterBox Aneu Series-skal med MagSafe till iPhone 13 Pro Max",
    price: 695,
    amount: 1,
    colors: ["black", "blue", "red"],
    imageUrls: [
      "/src/assets/img/iphone/iphone-3-black.jpg",
      "/src/assets/img/iphone/iphone-3-blue.jpg",
      "/src/assets/img/iphone/iphone-3-red.jpg",
    ],
  },
  {
    brand: "iphone",
    name: "iphone 4",
    description:
      "OtterBox Lumen Series-skal med MagSafe till iPhone 13 Pro Max",
    price: 495,
    amount: 1,
    colors: ["black", "blue", "orange"],
    imageUrls: [
      "/src/assets/img/iphone/iphone-4-black.jpg",
      "/src/assets/img/iphone/iphone-4-blue.jpg",
      "/src/assets/img/iphone/iphone-4-orange.jpg",
    ],
  },
  {
    brand: "iphone",
    name: "iphone 5",
    description:
      "OtterBox Core Series-skal till iPhone 14 Pro Max (MagSafe-kompatibelt)",
    price: 695,
    amount: 1,
    colors: ["black", "blue", "white"],
    imageUrls: [
      "/src/assets/img/iphone/iphone-5-black.jpg",
      "/src/assets/img/iphone/iphone-5-blue.jpg",
      "/src/assets/img/iphone/iphone-5-white.jpg",
    ],
  },
  {
    brand: "iphone",
    name: "iphone 6",
    description: "Läderfodral till iPhone 11 Pro Max",
    price: 595,
    amount: 1,
    colors: ["blue", "green", "purple"],
    imageUrls: [
      "/src/assets/img/iphone/iphone-6-blue.jpg",
      "/src/assets/img/iphone/iphone-6-green.jpg",
      "/src/assets/img/iphone/iphone-6-purple.jpg",
    ],
  },
  {
    brand: "iphone",
    name: "iphone 7",
    description: "Custom Phone Case till iphone 13 pro max",
    price: 695,
    amount: 1,
    colors: ["black", "blue", "pink"],
    imageUrls: [
      "/src/assets/img/iphone/iphone-7-black.jpg",
      "/src/assets/img/iphone/iphone-7-blue.jpg",
      "/src/assets/img/iphone/iphone-7-pink.jpg",
    ],
  },
  {
    brand: "iphone",
    name: "iphone 8",
    description: "SAGE till iphone 14 pro max",
    price: 495,
    amount: 1,
    colors: ["black", "green", "pink"],
    imageUrls: [
      "/src/assets/img/iphone/iphone-8-black.jpg",
      "/src/assets/img/iphone/iphone-8-green.jpg",
      "/src/assets/img/iphone/iphone-8-pink.jpg",
    ],
  },
  {
    brand: "iphone",
    name: "iphone 9",
    description: "BRAIDED ONYX till iphone 13 pro max",
    price: 695,
    amount: 1,
    colors: ["black", "blue", "brown"],
    imageUrls: [
      "/src/assets/img/iphone/iphone-9-black.jpg",
      "/src/assets/img/iphone/iphone-9-blue.jpg",
      "/src/assets/img/iphone/iphone-9-brown.jpg",
    ],
  },
  {
    brand: "iphone",
    name: "iphone 10",
    description: "Printed Case till iphone 14 pro max",
    price: 595,
    amount: 1,
    colors: ["black", "pink", "white"],
    imageUrls: [
      "/src/assets/img/iphone/iphone-10-black.jpg",
      "/src/assets/img/iphone/iphone-10-pink.jpg",
      "/src/assets/img/iphone/iphone-10-white.jpg",
    ],
  },
  {
    brand: "iphone",
    name: "iphone 11",
    description: "AZURA till iphone 13 pro",
    price: 695,
    amount: 1,
    colors: ["black", "blue", "white"],
    imageUrls: [
      "/src/assets/img/iphone/iphone-1-black.jpg",
      "/src/assets/img/iphone/iphone-1-blue.jpg",
      "/src/assets/img/iphone/iphone-1-white.jpg",
    ],
  },
  {
    brand: "iphone",
    name: "iphone 12",
    description: "SATIN till iphone 11 pro max",
    price: 595,
    amount: 1,
    colors: ["black", "pink", "white"],
    imageUrls: [
      "/src/assets/img/iphone/iphone-1-black.jpg",
      "/src/assets/img/iphone/iphone-1-pink.jpg",
      "/src/assets/img/iphone/iphone-1-white.jpg",
    ],
  },

  // Samsung

  {
    brand: "samsung",
    name: "samsung 1",
    description: "INTENSE till galaxy s20",
    price: 595,
    amount: 1,
    colors: ["black", "green", "pink"],
    imageUrls: [
      "/src/assets/img/samsung/samsung-1-black.jpg",
      "/src/assets/img/samsung/samsung-1-green.jpg",
      "/src/assets/img/samsung/samsung-1-pink.jpg",
    ],
  },

  {
    brand: "samsung",
    name: "samsung 2",
    description: "THUNDER MARBLE till galaxy s20",
    price: 695,
    amount: 1,
    colors: ["black", "gold", "white"],
    imageUrls: [
      "/src/assets/img/samsung/samsung-2-black.jpg",
      "/src/assets/img/samsung/samsung-2-gold.jpg",
      "/src/assets/img/samsung/samsung-2-white.jpg",
    ],
  },

  {
    brand: "samsung",
    name: "samsung 3",
    description: "THUNDER MARBLE till Galaxy S22 Ultra",
    price: 495,
    amount: 1,
    colors: ["black", "green", "white"],
    imageUrls: [
      "/src/assets/img/samsung/samsung-3-black.jpg",
      "/src/assets/img/samsung/samsung-3-green.jpg",
      "/src/assets/img/samsung/samsung-3-white.jpg",
    ],
  },
  {
    brand: "samsung",
    name: "samsung 4",
    description: "SMOKE till Galaxy S10+",
    price: 695,
    amount: 1,
    colors: ["black", "gold", "pink"],
    imageUrls: [
      "/src/assets/img/samsung/samsung-4-black.jpg",
      "/src/assets/img/samsung/samsung-4-gold.jpg",
      "/src/assets/img/samsung/samsung-4-pink.jpg",
    ],
  },
  {
    brand: "samsung",
    name: "samsung 5",
    description: "BRAIDED ONYX till Galaxy S20+",
    price: 595,
    amount: 1,
    colors: ["black", "green", "pink"],
    imageUrls: [
      "/src/assets/img/samsung/samsung-5-black.jpg",
      "/src/assets/img/samsung/samsung-5-green.jpg",
      "/src/assets/img/samsung/samsung-5-pink.jpg",
    ],
  },
  {
    brand: "samsung",
    name: "samsung 6",
    description: "METAL WOODS till Galaxy S21 Ultra",
    price: 695,
    amount: 1,
    colors: ["black", "green", "pink"],
    imageUrls: [
      "/src/assets/img/samsung/samsung-6-black.jpg",
      "/src/assets/img/samsung/samsung-6-green.jpg",
      "/src/assets/img/samsung/samsung-6-pink.jpg",
    ],
  },
  {
    brand: "samsung",
    name: "samsung 7",
    description: "GLOSSY till Galaxy S20",
    price: 495,
    amount: 1,
    colors: ["black", "green", "pink"],
    imageUrls: [
      "/src/assets/img/samsung/samsung-7-black.jpg",
      "/src/assets/img/samsung/samsung-7-green.jpg",
      "/src/assets/img/samsung/samsung-7-pink.jpg",
    ],
  },
  {
    brand: "samsung",
    name: "samsung 8",
    description: "THUNDER MARBLE till Galaxy S21+",
    price: 695,
    amount: 1,
    colors: ["black", "pink", "white"],
    imageUrls: [
      "/src/assets/img/samsung/samsung-8-black.jpg",
      "/src/assets/img/samsung/samsung-8-pink.jpg",
      "/src/assets/img/samsung/samsung-8-white.jpg",
    ],
  },
  {
    brand: "samsung",
    name: "samsung 9",
    description: "METAL till Galaxy S20",
    price: 595,
    amount: 1,
    colors: ["black", "green", "pink"],
    imageUrls: [
      "/src/assets/img/samsung/samsung-9-black.jpg",
      "/src/assets/img/samsung/samsung-9-green.jpg",
      "/src/assets/img/samsung/samsung-9-pink.jpg",
    ],
  },
  {
    brand: "samsung",
    name: "samsung 10",
    description: "SANDSTORM MARBLE till galaxy s10",
    price: 695,
    amount: 1,
    colors: ["black", "gold", "pink"],
    imageUrls: [
      "/src/assets/img/samsung/samsung-10-black.jpg",
      "/src/assets/img/samsung/samsung-10-gold.jpg",
      "/src/assets/img/samsung/samsung-10-pink.jpg",
    ],
  },
  {
    brand: "samsung",
    name: "samsung 11",
    description: "SAND MARBLE till Galaxy S20 Ultra",
    price: 695,
    amount: 1,
    colors: ["black", "gold", "green"],
    imageUrls: [
      "/src/assets/img/samsung/samsung-11-black.jpg",
      "/src/assets/img/samsung/samsung-11-gold.jpg",
      "/src/assets/img/samsung/samsung-11-green.jpg",
    ],
  },
  {
    brand: "samsung",
    name: "samsung 12",
    description: "Emerald Satin till Galaxy S20",
    price: 595,
    amount: 1,
    colors: ["black", "green", "white"],
    imageUrls: [
      "/src/assets/img/samsung/samsung-12-black.jpg",
      "/src/assets/img/samsung/samsung-12-green.jpg",
      "/src/assets/img/samsung/samsung-12-white.jpg",
    ],
  },
];
